---
title: 'Assignment 2: Data visualization'
author: 'Dora Czirfusz (VBNSF3)'
output: html_document
editor_options: 
chunk_output_type: console
---
library(tidyverse)
library(tidyr)
install.packages("scales")
library(scales)

## Task 1: Climbing expeditions

#reading data
df <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-22/expeditions.csv')

view(df)

#data cleaning
top <- df %>% mutate(peak_name = fct_lump(peak_name, n = 15)) %>% group_by(peak_name, season) %>%  summarise(counts = n(),.groups = 'drop') %>%  arrange(desc(counts))
  
top <- top[top$peak_name != "Other", , drop=FALSE]
top <- na.omit(top)

#plot
ggplot(top, aes(fct_reorder(peak_name, counts,.fun = sum), y = counts, fill = season)) + 
  geom_bar(stat = "identity") + 
  coord_flip() + 
  theme_light() +
  theme(legend.position="bottom") +
  scale_fill_viridis_d() +
  labs(title="The 15 most popular peaks stacked by season of expedition", x ="", y = "Number of expedition") 

## Task 2: PhDs awarded
#reading data
phd <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-19/phd_by_field.csv")

view(phd)

#data cleaning
group <- phd %>%	group_by(broad_field, year)	%>%	summarize(n = sum(n_phds, na.rm = T),.groups = 'drop')

#plot
ggplot(group, aes(x = year, y = n, colour = broad_field)) +
  scale_x_continuous(breaks = scales::pretty_breaks(5)) + 
  scale_y_continuous(labels = scales::comma_format(5)) +
  geom_line(size = 1.2) +
  scale_color_brewer(palette = "Dark2") +
  theme_minimal() +
  labs(x = "", y = "", title = "Number of awarded PhD-s in the US by year", colour = "Broad field")


## Task 3: Commute in the US
#reading data
work <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-11-05/commute.csv")

view(work)

#data cleaning
agg_w <- work %>% group_by(state_region, state_abb, mode) %>% summarise(n = sum(n, na.rm = T),.groups = 'drop')

split <- split(agg_w, agg_w$mode)
bike<- split[["Bike"]]
walk<- split[["Walk"]]

total <-merge(bike, walk, by=c("state_region","state_abb"), all = T)


#plot_breaks
base_breaks <- function(n = 5){
    function(x) {
        axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, n = n)
    }
}
#plot
ggplot(total, aes(x= n.x, y = n.y, colour = state_region)) +
  geom_point(size = 2) +
  geom_text(aes(label=state_abb),  size = 4, colour = "black", na.rm = T) +
  scale_x_log10(labels= scales::comma_format(5), breaks= base_breaks())+
  scale_y_log10(labels =scales::comma_format(5), breaks= base_breaks()) +
  theme_light() +
  labs(x = "Number of ppl walking to work (log N)", y = "Number of ppl biking to work (log N)", title = "Title number of people walking vs biking to work in each USA state", colour = "State region")
