---
title: "Assignment1: Cocktails"
author: Dora Czirfusz (VBNSF3)
output: html_notebook
---
#install.packages("tidyverse")
#install.packages("stringr", dependencies=TRUE)
#install.packages("magrittr")
#install.packages("curl")
#install.packages("readr")
library(tidyverse)
library(tidyr)
library(dplyr)
library(magrittr)
require(stringr)
library(curl)
library(readr)
## 1. Read the data
df <- read_tsv("https://raw.githubusercontent.com/nthun/cocktail-balance/master/cocktail_data.tsv")

View(df)

## 2. Transform the data table and clean the ingredient variable!
#ingredients to rows
df<- df %>% 
    mutate(ingredients = strsplit(as.character(ingredients), "<br/>")) %>% 
    unnest(ingredients)
    
#alcohol
df$ingredients <- sub("\\s*\\([^\\)]+\\)", "", df$ingredients)

#quantities
df$ingredients <- sub(".*oz|dashes|drops|dash|bsp|drop","", df$ingredients)
df$ingredients <- gsub('[[:digit:]]+', '', df$ingredients)

#checking variable
unique(df$ingredients)

#data cleaning
df$ingredients<-str_trim(df$ingredients)
df$ingredients <- gsub("<br> dash", "or", df$ingredients)
df$ingredients <- gsub('\u008f', 'ea', df$ingredients)
df$ingredients <- gsub('juiceor', 'juice or', df$ingredients)



## 3. All ingredients in alphabetical order
#optional ingredients
lista<- df %>% 
    mutate(ingredients = strsplit(as.character(ingredients), " or ")) %>% 
    unnest(ingredients)

#list
lista_abc <- as.data.frame(unique(lista$ingredients))
lista_abc <- sort(lista_abc, decreasing = FALSE)
view(lista_abc)
#list to text
sink("ingredients.txt")
print(lista_abc)
sink()


## 4. Number of unique ingredients
length(unique(lista$ingredients))

## 5. What are the top 10 ingredients?
df2 <- as.data.frame(table(lista$ingredients))

df2 %>%
  top_n(10)


## 6. Which cocktail(s) has/have the most ingredients?
agg <- df %>% group_by(name) %>% summarise(count_ingredients = n())
agg %>%
  top_n(1)
  
  
## 7. How many ingredients appear in only one cocktail (rare ingredient)?

rare <- df %>% count(ingredients)
rarelist<- rare %>%
  top_n(-1)

## 8. Which cocktail has an ingredient that is only used in one cocktail?

rarecoc <- merge(df,rarelist,by="ingredients")
rarecoc$name

## 9. What are the cocktails without rare ingredients?

nonrare <- anti_join(df, rarecoc, by = "name")
nonrare<- nonrare %>% count(name)
nonrare$name

## 10. Create a cheat sheet for the bartender!

cheat<- select(df, -c(abv,acid,sugar,type,index,instructions, ncotw))

cheat$X <- "1"

cheatsheet <- tapply(cheat$X, cheat[c("ingredients", "name")], mean)
