---
title: "Assignment 2, 2nd plot"
author: "Kovacs_Adel"
date: "1/2/2022"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

To remake this plot [here](https://github.com/elte-ppk-r-course/r_data_analysis_2122_fall/blob/master/assignments/assignment_2_plots/task2.png) first I have loaded the necessary packages and came back here every time I needed to add something

```{r, messages = FALSE}
library(tidytuesdayR)
library(forcats)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyr)
library(scales)
library(RColorBrewer)
```

Then I loaded the data

```{r, message = FALSE}
tt_data <- tt_load("2019-02-19")

phd_by_field <- tt_data$phd_by_field
phd_by_field

phd_by_field$broad_field <- as.factor(phd_by_field$broad_field)

phd_by_field$n_phds <- as.integer(phd_by_field$n_phds)
```

I needed a dataset where the winners are by year and by field

```{r}
sum_by_group <- phd_by_field %>%
  filter(n_phds != "NA") %>%
  group_by(broad_field, year) %>%
  summarize (Count =sum(n_phds))
sum_by_group
```

Then I made the plot

```{r}
ggplot(sum_by_group, aes(x=year, y=Count, color=broad_field)) +
  geom_line (size=1.2) +
  scale_x_continuous(breaks = pretty_breaks(6)) +
  scale_y_continuous(label = comma_format()) +
  scale_colour_brewer(palette="Dark2")+
  theme_minimal() +
  labs(title = "Number of awarded Ph.D.-s in the US by year") 
```

