---
title: "Assignment 6: Factor Analysis"
author: "Dora Czirfusz"
output: html_document
editor_options: 
  chunk_output_type: console
---
setwd("~/Desktop/PhD/kurzusok/R")
df<- read.csv("assignment5_dataset.csv", sep=";")

View(df)

#EDA
summary(df)

#recode
df$sex<- recode_factor(df$sex, "1" = "Male", "2"="Female")
df$party<- recode_factor(df$party, "1" = "democrat", "2" = "republican", "3" = "other", "4" = "none")

#plot
ggplot(df, aes(sex)) +
  geom_bar()
  
ggplot(df, aes(party)) +
  geom_bar()
  
ggplot(df, aes(liberal)) +
  geom_bar()
  
#testing normal distribution using Shapiro-Wilk
scale <- df[c(1:28)]
SW <- lapply(scale, shapiro.test)

result <- sapply(SW, `[`, c("statistic","p.value"))

t(result)

###non of the variables are normally distributed -› Spearman correlation suggested to be used

#correlation

scale_x <- as.matrix(scale)

#p values and r
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

cor<- rcorr(scale_x, type="spearman")
options(max.print=1000000)
flattenCorrMatrix(cor$r, cor$P)

#correlation coefficients
cor2<-lowerCor(scale, method="spearman")

#plotting correlation
corrplot(cor$r, type="upper", order="hclust",
         col=brewer.pal(n=5, name="RdYlBu"))
         
         
###strongest positive correlation are between ar13 & ar10; ar13 & ar26
###there are only moderate negative correlations

#testing for KMO
KMO(scale)

###KMO is 0,88, data is appropriate for EFA

#testing for MVN
mult.norm(scale)$mult.test

###according to the results, the  variables in our dataset do not follow a multivariate distribution, p<0,05 in each cases

#screeplot

eigen <- eigen(cor(scale, use = "complete.obs")) 
ap <- parallel(subject=nrow(scale),var=ncol(scale),
  rep=100,cent=.05)
nS <- nScree(x=eigen$values, aparallel=ap$eigen$qevpea)
plotnScree(nS)


###parallel analysis suggests 3 factors

#EFA
efa <- fa(scale, nfactors = 3, rotate="promax")
efa

#communalities
comm_s<- sort(efa$communality, decreasing = T)
comm_s
comm_m<-mean(efa$communality)
comm_m

###communalities are under 0.25 for ar18, 14, 22, 1, 3, 28, 8, 16 -› they need to be removed.
scale_sub<- dplyr::select(scale, -c(ar18, ar14, ar22, ar1, ar3, ar28, ar8, ar16))

##repeating steps##
#testing for KMO
KMO(scale_sub)

###KMO is 0,89, data is appropriate for EFA

#testing for MVN
mult.norm(scale_sub)$mult.test

###according to the results, the  variables in our dataset do not follow a multivariate distribution, p<0,05 in each cases

#screeplot

eigen <- eigen(cor(scale_sub, use = "complete.obs")) 
ap <- parallel(subject=nrow(scale_sub),var=ncol(scale_sub),
  rep=100,cent=.05)
nS <- nScree(x=eigen$values, aparallel=ap$eigen$qevpea)
plotnScree(nS)


###parallel analysis suggests 2 factors

#EFA
efa <- fa(scale_sub, nfactors = 2, rotate="promax")
efa

#communalities
comm_s<- sort(efa$communality, decreasing = T)
comm_s
comm_m<-mean(efa$communality)
comm_m

###ar21 & ar24 should be removed according to communalities

scale_sub2<- dplyr::select(scale_sub, -c(ar21, ar24))

##repeating steps##
#testing for KMO
KMO(scale_sub2)

###KMO is 0,89, data is appropriate for EFA

#testing for MVN
mult.norm(scale_sub2)$mult.test

###according to the results, the  variables in our dataset do not follow a multivariate distribution, p<0,05 in each cases

#screeplot

eigen <- eigen(cor(scale_sub2, use = "complete.obs")) 
ap <- parallel(subject=nrow(scale_sub2),var=ncol(scale_sub2),
  rep=100,cent=.05)
nS <- nScree(x=eigen$values, aparallel=ap$eigen$qevpea)
plotnScree(nS)


###parallel analysis suggests 2 factors

#EFA
efa <- fa(scale_sub2, nfactors = 2, rotate="promax")
efa

#communalities
comm_s<- sort(efa$communality, decreasing = T)
comm_s
comm_m<-mean(efa$communality)
comm_m


#loadings
load<-efa$loadings
load

#plotting the result of factor analysis
fa.diagram(efa)

###MR1 = opposition to animal testing
###MR2= opposition to animal-derived clothing or animal source foods

#scores
score<-efa$scores

###binding data###
df2 <- cbind(df,score)

df2 <- df2 %>%
  rename(anim_test=MR1, anim_use=MR2)

###log regression = ››› I used linear regression which was first mentioned in the task and seems appropriate for this analysis (later logistic regression appeared in the description)

lm <- lm(df2$liberal ~ df2$anim_test + df2$anim_use, data = df2)
lm

summary(lm)

resid <- resid(lm)
#testing normality of residuals
hist(lm$resid, main="Histogram of Residuals",
 ylab="Residuals")
 
shapiro.test(lm$resid)
 
####residuals are not normally distributed, linear regression should not be performed according to the assumptions
